//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assissmnt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public int taskid { get; set; }
        public string title { get; set; }
        public Nullable<int> useridd { get; set; }
        public string descr { get; set; }
        public string statuss { get; set; }
        public Nullable<System.DateTime> duedate { get; set; }
    
        public virtual users users { get; set; }
    }
}
